name: 'Mayhem for API'
on:
  workflow_call:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_JDK_VERSION: 11

jobs:
  build:
    ##################################################
    # Build
    ##################################################
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-2-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      ##################################################
      #
      # Launch the server
      #
      ##################################################
      - name: Run API
        run: |
            mvn compile exec:exec -pl dac/daemon & \
            timeout 600 bash -c 'until curl --fail localhost:9047/apiv2/server_status; do sleep 2; done'

      # Get a bearer token
      - name: Get admin Bearer Token on master realm
        run: |
          token=$( curl -X GET \
             -H 'Content-Type: application/json'\
             --data-raw '{"userName":"dremio","password":"dremio123"}'
             'http://localhost:9047/apiv2/login' | jq -j ".token")
          echo "AUTH_TOKEN=$token" >> "$GITHUB_ENV"

      ##################################################
      # Mayhem
      #
      # Run Mayhem for API. This will start a new run
      # against the REST API actively running on the
      # container launched earlier.
      #
      # Results will be collected in SAIRF formatted and
      # submitted to the codeql--action in order to report
      # API issues that are discovered.
      ##################################################
      - name: Run Mayhem for API to check for vulnerabilities
        uses: ForAllSecure/mapi-action@v1
        continue-on-error: true
        with:
          mapi-token: ${{ secrets.MAPI_TOKEN }}
          api-url: http://localhost:9047/admin/realms
          api-spec: .github/api/openapi_16.0.yml
          target: mayhemheroes/dremio-oss
          duration: 1min
          sarif-report: mapi.sarif
          html-report: mapi.html
          run-args: |
            --concurrency
            4
            --header-auth
            Authorization:Bearer ${{ env.AUTH_TOKEN }}
            --ignore-rule
            InvalidResponseSpec
            --ignore-endpoint
            .*logout.*

      ##################################################
      # Report
      #
      # An HTML report containing the the results of the
      # run are archived for later viewing, and a SARIF
      # (Static Analysis Results Interchange Format)
      # report produced and passed to codeQL. codeQL will
      # report any issues discovered in your Action results
      ##################################################
      - name: Archive Mayhem for API report
        uses: actions/upload-artifact@v2
        with:
          name: mapi-report
          path: mapi.html

      - name: Archive Mayhem for API SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: sarif-report
          path: mapi.sarif

      # Upload SARIF file (only available on public repos or github enterprise)
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: mapi.sarif